name: actor_critic
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - scipy
  - matplotlib
  - pandas
  - seaborn
  - jupyterlab
  - gymnasium
  - mujoco
  - glfw
  - pillow
  - cloudpickle
  - pytorch
  - pyyaml