action_bound: 1.0
alpha: 0.05
batch_size: 256
buffer_size: 1000000
ckpt_dir: checkpoints
device: cpu
gamma: 0.99
gradient_steps: 1
hidden_size: 256
lr: 0.0003
max_env_steps: 1000000
number_of_qs: 2
tau: 0.005
